import RoomOne from "../../../assets/fThreeHighStandingOne.jpg";
import RoomTwo from "../../../assets/fThreeHighStandingTwo.jpg";
import RoomThree from "../../../assets/fThreeHighStandingThree.jpg";
import RoomFour from "../../../assets/fThreeHighStandingFour.jpg";
import RoomFive from "../../../assets/fThreeHighStandingFive.jpg";
import RoomSix from "../../../assets/fThreeHighStandingSix.jpg";

const Boxes = [
  {
    id: 1,
    img: RoomOne,
    stats: "5000da / 100m²",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
  },

  {
    id: 2,
    img: RoomTwo,
    stats: "5000da / 100m²",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
  },

  {
    id: 3,
    img: RoomThree,
    stats: "5000da / 100m²",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
  },

  {
    id: 4,
    img: RoomFour,
    stats: "5000da / 100m²",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
  },

  {
    id: 5,
    img: RoomFive,
    stats: "5000da / 100m²",
    link: "fTroisAppartements",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
  },

  {
    id: 6,
    img: RoomSix,
    stats: "5000da / 100m²",
    link: "fTroisAppartements",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
  },
];

export default Boxes;
