import RoomOne from "../../../assets/fThreeHighStandingOne.jpg";
import RoomTwo from "../../../assets/fThreeHighStandingTwo.jpg";
import RoomThree from "../../../assets/fThreeHighStandingThree.jpg";
import RoomFour from "../../../assets/fThreeHighStandingFour.jpg";
import RoomFive from "../../../assets/fThreeHighStandingFive.jpg";
import RoomSix from "../../../assets/fThreeHighStandingSix.jpg";

const Data = [
  {
    id: 1,
    img: RoomOne,
    stats: "5000da / 100m²",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
    descriptionHeader: "Description",
    descriptionHeader_en: "Description",
    descriptionHeader_ar: "الوصف",
    descriptionParagraph:
      "Découvrez nos appartements de luxe de l'hôtel F3 avec un style moderne et trois espaces spacieux : une salle de séjour confortable et deux chambres confortables. L'expression (haut standing) signifie que nous utilisons des matériaux de première qualité et que nous proposons des équipements de luxe, pour vous offrir un lieu de séjour luxueux et apaisant. Profitez de l'expérience de luxe ultime dans nos appartements de l'hôtel F3, où nous nous concentrons sur chaque détail pour dépasser vos attentes.",
    descriptionParagraph_en:
      "Explore our deluxe F3 hotel apartments with a modern style and three roomy spaces: a cozy living area and two comfy bedrooms. The phrase (high standing) means we use top-notch materials and offer fancy amenities, giving you a luxurious and calming place to stay. Enjoy the ultimate luxury experience at our F3 hotel apartments, where we focus on every detail to surpass your expectations.",
    descriptionParagraph_ar:
      "استكشف شققنا الفندقية الفاخرة من طراز F3 ذات الطراز العصري وثلاث مساحات فسيحة: منطقة معيشة مريحة وغرفتي نوم مريحة. تعني عبارة (مكانة رفيعة) أننا نستخدم خامات من الدرجة الأولى ونوفر لك وسائل راحة فاخرة، مما يمنحك مكاناً فاخراً وهادئاً للإقامة. استمتع بتجربة الرفاهية المطلقة في شققنا الفندقية F3، حيث نركّز على كل التفاصيل لتجاوز توقعاتك.",
  },

  {
    id: 2,
    img: RoomTwo,
    stats: "5000da / 100m²",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
    descriptionHeader: "Description",
    descriptionHeader_en: "Description",
    descriptionHeader_ar: "الوصف",
    descriptionParagraph:
      "Découvrez nos appartements de luxe de l'hôtel F3 avec un style moderne et trois espaces spacieux : une salle de séjour confortable et deux chambres confortables. L'expression (haut standing) signifie que nous utilisons des matériaux de première qualité et que nous proposons des équipements de luxe, pour vous offrir un lieu de séjour luxueux et apaisant. Profitez de l'expérience de luxe ultime dans nos appartements de l'hôtel F3, où nous nous concentrons sur chaque détail pour dépasser vos attentes.",
    descriptionParagraph_en:
      "Explore our deluxe F3 hotel apartments with a modern style and three roomy spaces: a cozy living area and two comfy bedrooms. The phrase (high standing) means we use top-notch materials and offer fancy amenities, giving you a luxurious and calming place to stay. Enjoy the ultimate luxury experience at our F3 hotel apartments, where we focus on every detail to surpass your expectations.",
    descriptionParagraph_ar:
      "استكشف شققنا الفندقية الفاخرة من طراز F3 ذات الطراز العصري وثلاث مساحات فسيحة: منطقة معيشة مريحة وغرفتي نوم مريحة. تعني عبارة (مكانة رفيعة) أننا نستخدم خامات من الدرجة الأولى ونوفر لك وسائل راحة فاخرة، مما يمنحك مكاناً فاخراً وهادئاً للإقامة. استمتع بتجربة الرفاهية المطلقة في شققنا الفندقية F3، حيث نركّز على كل التفاصيل لتجاوز توقعاتك.",
  },

  {
    id: 3,
    img: RoomThree,
    stats: "5000da / 100m²",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
    descriptionHeader: "Description",
    descriptionHeader_en: "Description",
    descriptionHeader_ar: "الوصف",
    descriptionParagraph:
      "Découvrez nos appartements de luxe de l'hôtel F3 avec un style moderne et trois espaces spacieux : une salle de séjour confortable et deux chambres confortables. L'expression (haut standing) signifie que nous utilisons des matériaux de première qualité et que nous proposons des équipements de luxe, pour vous offrir un lieu de séjour luxueux et apaisant. Profitez de l'expérience de luxe ultime dans nos appartements de l'hôtel F3, où nous nous concentrons sur chaque détail pour dépasser vos attentes.",
    descriptionParagraph_en:
      "Explore our deluxe F3 hotel apartments with a modern style and three roomy spaces: a cozy living area and two comfy bedrooms. The phrase (high standing) means we use top-notch materials and offer fancy amenities, giving you a luxurious and calming place to stay. Enjoy the ultimate luxury experience at our F3 hotel apartments, where we focus on every detail to surpass your expectations.",
    descriptionParagraph_ar:
      "استكشف شققنا الفندقية الفاخرة من طراز F3 ذات الطراز العصري وثلاث مساحات فسيحة: منطقة معيشة مريحة وغرفتي نوم مريحة. تعني عبارة (مكانة رفيعة) أننا نستخدم خامات من الدرجة الأولى ونوفر لك وسائل راحة فاخرة، مما يمنحك مكاناً فاخراً وهادئاً للإقامة. استمتع بتجربة الرفاهية المطلقة في شققنا الفندقية F3، حيث نركّز على كل التفاصيل لتجاوز توقعاتك.",
  },

  {
    id: 4,
    img: RoomFour,
    stats: "5000da / 100m²",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
    descriptionHeader: "Description",
    descriptionHeader_en: "Description",
    descriptionHeader_ar: "الوصف",
    descriptionParagraph:
      "Découvrez nos appartements de luxe de l'hôtel F3 avec un style moderne et trois espaces spacieux : une salle de séjour confortable et deux chambres confortables. L'expression (haut standing) signifie que nous utilisons des matériaux de première qualité et que nous proposons des équipements de luxe, pour vous offrir un lieu de séjour luxueux et apaisant. Profitez de l'expérience de luxe ultime dans nos appartements de l'hôtel F3, où nous nous concentrons sur chaque détail pour dépasser vos attentes.",
    descriptionParagraph_en:
      "Explore our deluxe F3 hotel apartments with a modern style and three roomy spaces: a cozy living area and two comfy bedrooms. The phrase (high standing) means we use top-notch materials and offer fancy amenities, giving you a luxurious and calming place to stay. Enjoy the ultimate luxury experience at our F3 hotel apartments, where we focus on every detail to surpass your expectations.",
    descriptionParagraph_ar:
      "استكشف شققنا الفندقية الفاخرة من طراز F3 ذات الطراز العصري وثلاث مساحات فسيحة: منطقة معيشة مريحة وغرفتي نوم مريحة. تعني عبارة (مكانة رفيعة) أننا نستخدم خامات من الدرجة الأولى ونوفر لك وسائل راحة فاخرة، مما يمنحك مكاناً فاخراً وهادئاً للإقامة. استمتع بتجربة الرفاهية المطلقة في شققنا الفندقية F3، حيث نركّز على كل التفاصيل لتجاوز توقعاتك.",
  },

  {
    id: 5,
    img: RoomFive,
    stats: "5000da / 100m²",
    link: "fTroisAppartements",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
    descriptionHeader: "Description",
    descriptionHeader_en: "Description",
    descriptionHeader_ar: "الوصف",
    descriptionParagraph:
      "Découvrez nos appartements de luxe de l'hôtel F3 avec un style moderne et trois espaces spacieux : une salle de séjour confortable et deux chambres confortables. L'expression (haut standing) signifie que nous utilisons des matériaux de première qualité et que nous proposons des équipements de luxe, pour vous offrir un lieu de séjour luxueux et apaisant. Profitez de l'expérience de luxe ultime dans nos appartements de l'hôtel F3, où nous nous concentrons sur chaque détail pour dépasser vos attentes.",
    descriptionParagraph_en:
      "Explore our deluxe F3 hotel apartments with a modern style and three roomy spaces: a cozy living area and two comfy bedrooms. The phrase (high standing) means we use top-notch materials and offer fancy amenities, giving you a luxurious and calming place to stay. Enjoy the ultimate luxury experience at our F3 hotel apartments, where we focus on every detail to surpass your expectations.",
    descriptionParagraph_ar:
      "استكشف شققنا الفندقية الفاخرة من طراز F3 ذات الطراز العصري وثلاث مساحات فسيحة: منطقة معيشة مريحة وغرفتي نوم مريحة. تعني عبارة (مكانة رفيعة) أننا نستخدم خامات من الدرجة الأولى ونوفر لك وسائل راحة فاخرة، مما يمنحك مكاناً فاخراً وهادئاً للإقامة. استمتع بتجربة الرفاهية المطلقة في شققنا الفندقية F3، حيث نركّز على كل التفاصيل لتجاوز توقعاتك.",
  },

  {
    id: 6,
    img: RoomSix,
    stats: "5000da / 100m²",
    link: "fTroisAppartements",
    button: "Plus de détails",
    button_en: "More details",
    button_ar: "المزيد من التفاصيل",
    new: "Nouveau",
    new_en: "New",
    new_ar: "جديد",
    price: "5000da",
    day: "Jour",
    day_en: "Day",
    day_ar: "يوم",
    room: "3 chambres",
    room_en: "3 rooms",
    room_ar: "3 غرف",
    bath: "1 salle de bain",
    bath_en: "1 bethroom",
    bath_ar: "1 حمام",
    title: "Maisons de luxe extraordinaires.",
    title_en: "Extraordinary Luxury Homes.",
    title_ar: " شقق راقية.",
    descriptionHeader: "Description",
    descriptionHeader_en: "Description",
    descriptionHeader_ar: "الوصف",
    descriptionParagraph:
      "Découvrez nos appartements de luxe de l'hôtel F3 avec un style moderne et trois espaces spacieux : une salle de séjour confortable et deux chambres confortables. L'expression (haut standing) signifie que nous utilisons des matériaux de première qualité et que nous proposons des équipements de luxe, pour vous offrir un lieu de séjour luxueux et apaisant. Profitez de l'expérience de luxe ultime dans nos appartements de l'hôtel F3, où nous nous concentrons sur chaque détail pour dépasser vos attentes.",
    descriptionParagraph_en:
      "Explore our deluxe F3 hotel apartments with a modern style and three roomy spaces: a cozy living area and two comfy bedrooms. The phrase (high standing) means we use top-notch materials and offer fancy amenities, giving you a luxurious and calming place to stay. Enjoy the ultimate luxury experience at our F3 hotel apartments, where we focus on every detail to surpass your expectations.",
    descriptionParagraph_ar:
      "استكشف شققنا الفندقية الفاخرة من طراز F3 ذات الطراز العصري وثلاث مساحات فسيحة: منطقة معيشة مريحة وغرفتي نوم مريحة. تعني عبارة (مكانة رفيعة) أننا نستخدم خامات من الدرجة الأولى ونوفر لك وسائل راحة فاخرة، مما يمنحك مكاناً فاخراً وهادئاً للإقامة. استمتع بتجربة الرفاهية المطلقة في شققنا الفندقية F3، حيث نركّز على كل التفاصيل لتجاوز توقعاتك.",
  },
];

export default Data;
